### PR TITLE
fix: Stop blocking the async runtime when connecting to quilc or a QPU.

### LINKED ISSUE #31: Stop blocking the Tokio runtime
If connecting to `quilc` or the eventual QPU over RPCQ fails, the SDK currently just spins indefinitely. A timeout should be set (and preferably configurable) so that the SDK gives up on executing and specifies where it failed (was it quilc or QPU connection).

### PR DESCRIPTION
**Pull request by dbanty**
Closes #31

This basically introduces threads to run all the RPCQ connections inside of. As a result, there's some `Arc`ing and `Box`ing. This PR will result in a bit slower performance overall but I think it's well worth it to not block the runtime. Importantly, this also enables callers to use timeouts if they want to give up eventually rather than waiting forever.

### CODE REVIEW

File: qcs/src/executable.rs [hunk 1]
```diff
@@ -81,9 +82,9 @@ impl<'executable> Executable<'executable, '_> {
     /// 1. `quil` is a string slice representing the original program to be run. The returned
     ///     [`Executable`] will only live as long as this reference.
     #[must_use]
-    pub fn from_quil(quil: &'executable str) -> Self {
+    pub fn from_quil<Quil: Into<Arc<str>>>(quil: Quil) -> Self {
```
Comment (nilslice) [inline qcs/src/executable.rs:85]: Maybe personal preference, but I tend to shy away from long generic names vs. single letter (`Q` over `Quil`), only because it can be confusing for folks less familiar with the concept & mistake it for a variable or something.

File: qcs/src/executable.rs [hunk 2]
```diff
@@ -185,28 +186,24 @@ impl<'executable> Executable<'executable, '_> {
     /// ```
     ///
     /// [parametric compilation]: https://pyquil-docs.rigetti.com/en/stable/basics.html?highlight=parametric#parametric-compilation
-    pub fn with_parameter(
+    pub fn with_parameter<Param: Into<Box<str>>>(
```
Comment (nilslice) [inline qcs/src/executable.rs:189]: Similarly, here `P` over `Param`

File: qcs/src/qpu/execution.rs [hunk 3]
```diff
@@ -90,11 +92,16 @@ impl<'a> Execution<'a> {
...
             trace!("Converting to Native Quil");
-            quilc::compile_program(quil, &isa, config)
-                .wrap_err("When attempting to compile your program to Native Quil")?
+            let thread_config = config.clone();
+            spawn_blocking(move || {
+                quilc::compile_program(&quil, &isa, &thread_config)
+                    .wrap_err("When attempting to compile your program to Native Quil")
+            })
+            .await
+            .map_err(|_| eyre!("Error in quilc thread."))??
```
Comment (nilslice) [inline qcs/src/qpu/execution.rs:101]: nit: `s/thread/task`, just to be consistent with the underlying runtime.

File: qcs/src/qpu/execution.rs [hunk 4]
```diff
@@ -243,7 +260,12 @@ impl<'a> Execution<'a> {
                     })
             })
             .collect::<Result<Vec<f64>>>()?;
-        patch_values.insert(SUBSTITUTION_NAME, values);
+        // Convert back to the format that this library expects
+        let mut patch_values: Parameters = params
+            .into_iter()
+            .map(|(key, value)| (key.into(), value))
+            .collect();
+        patch_values.insert(SUBSTITUTION_NAME.into(), values);
```
Comment (nilslice) [inline qcs/src/qpu/execution.rs:268]: I don't think there is a test covering this, but I might have missed it. Might be good to add one, since based on the comments "this library expects" and "that quil-rs expects", we would benefit from those invariants being checked for regression over time.

**Review by nilslice — CHANGES_REQUESTED** [review]
See note about testing the substitution / format things - maybe super minor and in that case no worries.. the renaming of the generic params is certainly personal preference, but might be worth considering since we also use exact or similar names as variables or types throughout (Parameters, quil, etc).

File: qcs/src/executable.rs (hunk 1 above)
Comment (dbanty) [reply qcs/src/executable.rs:85]: I have a pretty strong preference for more descriptive generic names simply because I've found it frustrating to trace types for single letters, particularly when there are multiple generics it becomes pretty unreadable (e.g., in `tokio` their generic type for `response` tends to be `S` because `R` is taken up by `request`... or maybe it's the other way around, I can never remember).

For a short signature like this, it doesn't make much of a difference, but since I want consistency in the naming convention, I try to always stick to naming the generic after the thing it's typing.

File: qcs/src/qpu/execution.rs (hunk 3 above)
Comment (dbanty) [reply qcs/src/qpu/execution.rs:101]:
```suggestion
            .map_err(|_| eyre!("Task running quilc did not complete."))??
```

File: qcs/src/qpu/execution.rs (hunk 4 above)
Comment (dbanty) [reply qcs/src/qpu/execution.rs:268]: It's really a type conversion—this would not compile if it wasn't converting correctly. We have a `HashMap<Box<str>, Vec<f64>>` and `quil-rs` wants a `HashMap<&str, Vec<f64>>`. The comment is just to clarify the fact that this iteration looks kinda useless.

Is there a better comment I could leave to reduce confusion?

File: qcs/src/executable.rs (hunk 1 above)
Comment (nilslice) [reply qcs/src/executable.rs:85]: Ok that's fair, yea not a major thing!

File: qcs/src/qpu/execution.rs (hunk 4 above)
Comment (nilslice) [reply qcs/src/qpu/execution.rs:268]: I see -- that's good enough for me :) Thanks for clarifying.

**Review by nilslice — APPROVED** [review]
