### PR TITLE
fix: deserialize null fidelity and duration as "perfect" values

### LINKED ISSUE #179: Deserialize `null` fidelity and duration as "perfect" values
When pyQuil provides a `TargetDevice` that is based on a physical device (e.g. `Aspen-11`) it will have numeric fidelity and duration values. If instead pyQuil provides a `TargetDevice` that is a non-physical device (e.g. `8q-qvm`) it will have `null` fidelity and duration values. This is generally handled by patching `null` with "perfect" values.

### PR DESCRIPTION
**Pull request by notmgsk**
See attached issue for details.

Closes #179.

### CODE REVIEW

**Review by MarquessV — APPROVED** [review]

File: crates/lib/src/qpu/quilc/isa/operator.rs [hunk 1]
```diff
@@ -18,23 +18,47 @@ pub(crate) fn wildcard(node_id: Option<i32>) -> Operator {
 pub(crate) enum Operator {
     Gate {
         operator: String,
+        #[serde(deserialize_with = "deserialize_duration_null_default")]
```
Comment (Shadow53) [inline crates/lib/src/qpu/quilc/isa/operator.rs:21]: Can you not just do this and leave out the manual deserializer stuff?
```suggestion
        #[serde(default = "PERFECT_DURATION")]
```

**Review by Shadow53 — COMMENTED** [review]
Seems like this could be simplified...

File: crates/lib/src/qpu/quilc/isa/operator.rs (hunk 1 above)
Comment (notmgsk) [reply crates/lib/src/qpu/quilc/isa/operator.rs:21]: `default` expects a function, so it's not quite _that_ simple, but it can be improved with e.g.
```rust
fn deserialize_duration_null_default() -> f64 {
    PERFECT_DURATION
}
```

Comment (Shadow53) [reply crates/lib/src/qpu/quilc/isa/operator.rs:21]: I saw you added `simplify default` and `Revert "simplify default"` commits, so I tried using a default function locally. Looks like an explicit `null` is considered invalid for a `f64` field. So it looks like the deserializer is needed after all :/
